apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: argocd-sumeet-bucket
  labels:
    example: "true"
  annotations:
    # Note that this will be the actual bucket name so it has to be globally unique/available.
    crossplane.io/external-name: crossplane-argo-example-bucket
spec:
  location: US
  storageClass: MULTI_REGIONAL
  providerConfigRef:
    name: crossplane-provider-gcp 
  deletionPolicy: Delete
