---
apiVersion: storage.gcp.crossplane.io/v1alpha1
kind: BucketPolicyMember
metadata:
  name: crossplane-example-bucket-bind-member-to-role
spec:
  forProvider:
    bucketRef:
      name: argocd-sumeet-bucket
    # member: serviceAccount:<my-sa-email>
    serviceAccountMemberRef:
      name: arg-bucket-sa
    role: roles/storage.objectAdmin
  providerConfigRef:
    name: crossplane-provider-gcp
