apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Subnetwork
metadata:
  name: crossplane-subnetwork
  labels:
     service: subnetwork
     creation: crossplane
spec:
  forProvider:
    region: us-central1 #change if required
    ipCidrRange: "192.168.0.0/16" #change if required
    privateIpGoogleAccess: true
    networkSelector:
      matchLabels:
       service: vpc 
       creation: crossplane
  providerConfigRef:
    name: crossplane-provider-gcp